apiVersion: v1
kind: Service
metadata:
  name: slackin-app
  labels:
    app: slackin
    role: web
    tier: frontend
    release: stable
    environment: production
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: slackin
    release: stable
    environment: production
    tier: frontend
  type: LoadBalancer
---
#
# Slackin Application
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slackin-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: slackin
        role: web
        tier: frontend
        release: stable
        environment: production
    spec:
      containers:
        - name: slackin-web
          image: us.gcr.io/freestar-157323/slackin-app:0.1.0
          env:
            - name: SLACK_SUBDOMAIN
              value: FREECOLLECTIVE
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slackin-env
                  key: slack_api_token
          ports:
            - containerPort: 3000
              name: slackin-app
